"""
Seed Data Extraction and Management

Provides the foundational verbs, nouns, and existing task references
for the verb-noun matrix generation strategy.
"""

from dataclasses import dataclass, field
from typing import Optional
import json


@dataclass
class VerbEntry:
    """A verb with metadata for task generation."""
    verb: str
    language: str
    category: str
    transitivity: str  # transitive, intransitive, both
    typical_objects: list[str] = field(default_factory=list)
    physical_involvement: str = "medium"  # none, low, medium, high
    aliases: list[str] = field(default_factory=list)


@dataclass
class NounEntry:
    """A noun with metadata for task generation."""
    noun: str
    language: str
    category: str
    is_countable: bool = True
    typical_actions: list[str] = field(default_factory=list)
    physical_properties: dict = field(default_factory=dict)  # fragile, heavy, etc.
    cultural_context: Optional[str] = None  # If culturally specific


# =============================================================================
# ENGLISH SEED VERBS (Comprehensive, categorized)
# =============================================================================

ENGLISH_VERBS = [
    # MANIPULATION - Grasping and holding
    VerbEntry("grasp", "en", "manipulation", "transitive", ["object", "handle", "tool"], "high"),
    VerbEntry("grip", "en", "manipulation", "transitive", ["handle", "bar", "rope"], "high"),
    VerbEntry("hold", "en", "manipulation", "transitive", ["object", "baby", "cup"], "medium"),
    VerbEntry("release", "en", "manipulation", "transitive", ["object", "grip", "button"], "low"),
    VerbEntry("pinch", "en", "manipulation", "transitive", ["object", "skin", "salt"], "medium"),
    VerbEntry("squeeze", "en", "manipulation", "transitive", ["bottle", "sponge", "fruit"], "high"),
    
    # MANIPULATION - Moving objects
    VerbEntry("lift", "en", "manipulation", "transitive", ["box", "weight", "child"], "high"),
    VerbEntry("lower", "en", "manipulation", "transitive", ["object", "blinds", "volume"], "medium"),
    VerbEntry("push", "en", "manipulation", "transitive", ["door", "cart", "button"], "medium"),
    VerbEntry("pull", "en", "manipulation", "transitive", ["door", "rope", "drawer"], "medium"),
    VerbEntry("drag", "en", "manipulation", "transitive", ["furniture", "file", "body"], "high"),
    VerbEntry("slide", "en", "manipulation", "transitive", ["drawer", "door", "card"], "low"),
    VerbEntry("carry", "en", "manipulation", "transitive", ["bag", "child", "tray"], "high"),
    VerbEntry("place", "en", "manipulation", "transitive", ["object", "dish", "book"], "low"),
    VerbEntry("drop", "en", "manipulation", "transitive", ["object", "ball", "anchor"], "low"),
    VerbEntry("throw", "en", "manipulation", "transitive", ["ball", "trash", "dice"], "medium"),
    VerbEntry("catch", "en", "manipulation", "transitive", ["ball", "object", "fish"], "medium"),
    VerbEntry("toss", "en", "manipulation", "transitive", ["salad", "coin", "ball"], "low"),
    VerbEntry("flip", "en", "manipulation", "transitive", ["pancake", "page", "switch"], "low"),
    VerbEntry("rotate", "en", "manipulation", "transitive", ["dial", "object", "wheel"], "low"),
    VerbEntry("twist", "en", "manipulation", "transitive", ["cap", "knob", "wire"], "medium"),
    VerbEntry("turn", "en", "manipulation", "transitive", ["page", "knob", "wheel"], "low"),
    VerbEntry("spin", "en", "manipulation", "transitive", ["top", "wheel", "bottle"], "low"),
    VerbEntry("roll", "en", "manipulation", "transitive", ["dough", "ball", "dice"], "low"),
    VerbEntry("shake", "en", "manipulation", "transitive", ["bottle", "hand", "dice"], "medium"),
    VerbEntry("stir", "en", "manipulation", "transitive", ["soup", "coffee", "mixture"], "low"),
    VerbEntry("mix", "en", "manipulation", "transitive", ["ingredients", "paint", "drinks"], "medium"),
    VerbEntry("pour", "en", "manipulation", "transitive", ["water", "drink", "concrete"], "low"),
    VerbEntry("scoop", "en", "manipulation", "transitive", ["ice cream", "rice", "sand"], "low"),
    VerbEntry("spread", "en", "manipulation", "transitive", ["butter", "jam", "cream"], "low"),
    VerbEntry("wipe", "en", "manipulation", "transitive", ["surface", "table", "face"], "low"),
    VerbEntry("scrub", "en", "manipulation", "transitive", ["floor", "pot", "skin"], "medium"),
    VerbEntry("rub", "en", "manipulation", "transitive", ["surface", "lotion", "eyes"], "low"),
    VerbEntry("polish", "en", "manipulation", "transitive", ["shoes", "silver", "car"], "medium"),
    VerbEntry("brush", "en", "manipulation", "transitive", ["hair", "teeth", "surface"], "low"),
    VerbEntry("comb", "en", "manipulation", "transitive", ["hair", "fiber"], "low"),
    VerbEntry("sweep", "en", "manipulation", "transitive", ["floor", "debris", "room"], "medium"),
    VerbEntry("mop", "en", "manipulation", "transitive", ["floor", "spill"], "medium"),
    VerbEntry("vacuum", "en", "manipulation", "transitive", ["floor", "carpet", "car"], "medium"),
    VerbEntry("dust", "en", "manipulation", "transitive", ["furniture", "shelf", "surface"], "low"),
    
    # MANIPULATION - Cutting and shaping
    VerbEntry("cut", "en", "manipulation", "transitive", ["paper", "food", "fabric"], "medium"),
    VerbEntry("slice", "en", "manipulation", "transitive", ["bread", "fruit", "meat"], "medium"),
    VerbEntry("chop", "en", "manipulation", "transitive", ["vegetables", "wood", "onion"], "high"),
    VerbEntry("dice", "en", "manipulation", "transitive", ["vegetables", "fruit", "meat"], "medium"),
    VerbEntry("mince", "en", "manipulation", "transitive", ["garlic", "meat", "herbs"], "medium"),
    VerbEntry("peel", "en", "manipulation", "transitive", ["fruit", "vegetable", "sticker"], "low"),
    VerbEntry("grate", "en", "manipulation", "transitive", ["cheese", "carrot", "ginger"], "medium"),
    VerbEntry("shred", "en", "manipulation", "transitive", ["paper", "cabbage", "chicken"], "medium"),
    VerbEntry("tear", "en", "manipulation", "transitive", ["paper", "fabric", "lettuce"], "low"),
    VerbEntry("rip", "en", "manipulation", "transitive", ["paper", "fabric", "package"], "medium"),
    VerbEntry("break", "en", "manipulation", "transitive", ["egg", "stick", "bread"], "medium"),
    VerbEntry("crack", "en", "manipulation", "transitive", ["egg", "nut", "knuckles"], "low"),
    VerbEntry("crush", "en", "manipulation", "transitive", ["garlic", "can", "ice"], "high"),
    VerbEntry("smash", "en", "manipulation", "transitive", ["bug", "ball", "window"], "high"),
    VerbEntry("grind", "en", "manipulation", "transitive", ["coffee", "pepper", "meat"], "medium"),
    VerbEntry("mash", "en", "manipulation", "transitive", ["potato", "banana", "avocado"], "medium"),
    VerbEntry("blend", "en", "manipulation", "transitive", ["smoothie", "soup", "colors"], "low"),
    VerbEntry("whisk", "en", "manipulation", "transitive", ["eggs", "cream", "batter"], "medium"),
    VerbEntry("beat", "en", "manipulation", "transitive", ["eggs", "cream", "drum"], "medium"),
    VerbEntry("knead", "en", "manipulation", "transitive", ["dough", "clay", "muscle"], "high"),
    VerbEntry("fold", "en", "manipulation", "transitive", ["paper", "clothes", "batter"], "low"),
    VerbEntry("unfold", "en", "manipulation", "transitive", ["paper", "napkin", "map"], "low"),
    VerbEntry("wrap", "en", "manipulation", "transitive", ["gift", "food", "bandage"], "low"),
    VerbEntry("unwrap", "en", "manipulation", "transitive", ["gift", "candy", "package"], "low"),
    VerbEntry("tie", "en", "manipulation", "transitive", ["shoelace", "knot", "rope"], "medium"),
    VerbEntry("untie", "en", "manipulation", "transitive", ["shoelace", "knot", "ribbon"], "low"),
    VerbEntry("knot", "en", "manipulation", "transitive", ["rope", "tie", "thread"], "medium"),
    VerbEntry("braid", "en", "manipulation", "transitive", ["hair", "rope", "bread"], "medium"),
    VerbEntry("weave", "en", "manipulation", "transitive", ["fabric", "basket", "story"], "medium"),
    VerbEntry("sew", "en", "manipulation", "transitive", ["fabric", "button", "wound"], "medium"),
    VerbEntry("stitch", "en", "manipulation", "transitive", ["fabric", "wound", "pattern"], "medium"),
    VerbEntry("thread", "en", "manipulation", "transitive", ["needle", "beads", "pipe"], "low"),
    VerbEntry("pin", "en", "manipulation", "transitive", ["fabric", "paper", "hair"], "low"),
    VerbEntry("clip", "en", "manipulation", "transitive", ["paper", "hair", "nails"], "low"),
    VerbEntry("staple", "en", "manipulation", "transitive", ["paper", "fabric"], "low"),
    VerbEntry("tape", "en", "manipulation", "transitive", ["paper", "box", "wire"], "low"),
    VerbEntry("glue", "en", "manipulation", "transitive", ["paper", "wood", "plastic"], "low"),
    VerbEntry("stick", "en", "manipulation", "transitive", ["sticker", "label", "poster"], "low"),
    VerbEntry("attach", "en", "manipulation", "transitive", ["file", "document", "part"], "low"),
    VerbEntry("detach", "en", "manipulation", "transitive", ["part", "cable", "label"], "low"),
    VerbEntry("connect", "en", "manipulation", "transitive", ["cable", "pipe", "dots"], "low"),
    VerbEntry("disconnect", "en", "manipulation", "transitive", ["cable", "pipe", "device"], "low"),
    VerbEntry("plug", "en", "manipulation", "transitive", ["cable", "hole", "drain"], "low"),
    VerbEntry("unplug", "en", "manipulation", "transitive", ["device", "cable", "drain"], "low"),
    VerbEntry("insert", "en", "manipulation", "transitive", ["key", "card", "needle"], "low"),
    VerbEntry("remove", "en", "manipulation", "transitive", ["object", "stain", "part"], "low"),
    VerbEntry("extract", "en", "manipulation", "transitive", ["tooth", "juice", "data"], "medium"),
    VerbEntry("install", "en", "manipulation", "transitive", ["software", "appliance", "fixture"], "medium"),
    VerbEntry("uninstall", "en", "manipulation", "transitive", ["software", "appliance"], "low"),
    VerbEntry("assemble", "en", "manipulation", "transitive", ["furniture", "puzzle", "team"], "medium"),
    VerbEntry("disassemble", "en", "manipulation", "transitive", ["furniture", "device", "gun"], "medium"),
    VerbEntry("build", "en", "manipulation", "transitive", ["house", "model", "fire"], "high"),
    VerbEntry("construct", "en", "manipulation", "transitive", ["building", "argument", "sentence"], "high"),
    VerbEntry("demolish", "en", "manipulation", "transitive", ["building", "wall", "argument"], "high"),
    VerbEntry("repair", "en", "manipulation", "transitive", ["car", "device", "relationship"], "medium"),
    VerbEntry("fix", "en", "manipulation", "transitive", ["problem", "device", "meal"], "medium"),
    VerbEntry("adjust", "en", "manipulation", "transitive", ["settings", "mirror", "volume"], "low"),
    VerbEntry("calibrate", "en", "manipulation", "transitive", ["instrument", "scale", "display"], "low"),
    VerbEntry("tighten", "en", "manipulation", "transitive", ["screw", "belt", "grip"], "medium"),
    VerbEntry("loosen", "en", "manipulation", "transitive", ["screw", "belt", "grip"], "low"),
    VerbEntry("screw", "en", "manipulation", "transitive", ["bolt", "lid", "part"], "medium"),
    VerbEntry("unscrew", "en", "manipulation", "transitive", ["lid", "bolt", "part"], "medium"),
    VerbEntry("hammer", "en", "manipulation", "transitive", ["nail", "metal", "point"], "high"),
    VerbEntry("nail", "en", "manipulation", "transitive", ["wood", "picture", "landing"], "medium"),
    VerbEntry("drill", "en", "manipulation", "transitive", ["hole", "wall", "team"], "medium"),
    VerbEntry("saw", "en", "manipulation", "transitive", ["wood", "metal", "branch"], "high"),
    VerbEntry("sand", "en", "manipulation", "transitive", ["wood", "surface", "floor"], "medium"),
    VerbEntry("file", "en", "manipulation", "transitive", ["nail", "metal", "document"], "low"),
    VerbEntry("sharpen", "en", "manipulation", "transitive", ["knife", "pencil", "skills"], "low"),
    VerbEntry("paint", "en", "manipulation", "transitive", ["wall", "picture", "nails"], "medium"),
    VerbEntry("draw", "en", "manipulation", "transitive", ["picture", "line", "conclusion"], "low"),
    VerbEntry("sketch", "en", "manipulation", "transitive", ["drawing", "plan", "idea"], "low"),
    VerbEntry("write", "en", "manipulation", "transitive", ["letter", "code", "story"], "low"),
    VerbEntry("type", "en", "manipulation", "transitive", ["document", "message", "code"], "low"),
    VerbEntry("erase", "en", "manipulation", "transitive", ["mistake", "drawing", "data"], "low"),
    VerbEntry("delete", "en", "manipulation", "transitive", ["file", "message", "account"], "none"),
    VerbEntry("copy", "en", "manipulation", "transitive", ["document", "file", "behavior"], "low"),
    VerbEntry("paste", "en", "manipulation", "transitive", ["text", "image", "wallpaper"], "low"),
    VerbEntry("print", "en", "manipulation", "transitive", ["document", "photo", "shirt"], "low"),
    VerbEntry("scan", "en", "manipulation", "transitive", ["document", "room", "barcode"], "low"),
    VerbEntry("photograph", "en", "manipulation", "transitive", ["scene", "person", "document"], "low"),
    VerbEntry("record", "en", "manipulation", "transitive", ["video", "audio", "data"], "low"),
    VerbEntry("measure", "en", "manipulation", "transitive", ["length", "ingredients", "performance"], "low"),
    VerbEntry("weigh", "en", "manipulation", "transitive", ["object", "options", "ingredients"], "low"),
    VerbEntry("count", "en", "manipulation", "transitive", ["objects", "money", "votes"], "none"),
    VerbEntry("sort", "en", "manipulation", "transitive", ["items", "laundry", "data"], "low"),
    VerbEntry("arrange", "en", "manipulation", "transitive", ["flowers", "furniture", "meeting"], "low"),
    VerbEntry("organize", "en", "manipulation", "transitive", ["closet", "event", "files"], "low"),
    VerbEntry("stack", "en", "manipulation", "transitive", ["boxes", "plates", "chairs"], "low"),
    VerbEntry("pile", "en", "manipulation", "transitive", ["clothes", "papers", "sand"], "low"),
    VerbEntry("hang", "en", "manipulation", "transitive", ["picture", "clothes", "ornament"], "low"),
    VerbEntry("mount", "en", "manipulation", "transitive", ["TV", "picture", "horse"], "medium"),
    VerbEntry("display", "en", "manipulation", "transitive", ["product", "art", "emotion"], "low"),
    VerbEntry("store", "en", "manipulation", "transitive", ["food", "data", "luggage"], "low"),
    VerbEntry("pack", "en", "manipulation", "transitive", ["suitcase", "box", "bags"], "medium"),
    VerbEntry("unpack", "en", "manipulation", "transitive", ["suitcase", "box", "groceries"], "low"),
    VerbEntry("load", "en", "manipulation", "transitive", ["truck", "dishwasher", "gun"], "medium"),
    VerbEntry("unload", "en", "manipulation", "transitive", ["truck", "dishwasher", "cargo"], "medium"),
    VerbEntry("fill", "en", "manipulation", "transitive", ["container", "form", "tank"], "low"),
    VerbEntry("empty", "en", "manipulation", "transitive", ["container", "trash", "room"], "low"),
    VerbEntry("drain", "en", "manipulation", "transitive", ["sink", "pasta", "battery"], "low"),
    
    # MANIPULATION - Cooking specific
    VerbEntry("cook", "en", "manipulation", "transitive", ["food", "meal", "dinner"], "medium"),
    VerbEntry("bake", "en", "manipulation", "transitive", ["bread", "cake", "cookies"], "low"),
    VerbEntry("roast", "en", "manipulation", "transitive", ["meat", "vegetables", "coffee"], "low"),
    VerbEntry("grill", "en", "manipulation", "transitive", ["meat", "vegetables", "sandwich"], "medium"),
    VerbEntry("fry", "en", "manipulation", "transitive", ["egg", "chicken", "vegetables"], "medium"),
    VerbEntry("saute", "en", "manipulation", "transitive", ["vegetables", "meat", "onions"], "low"),
    VerbEntry("boil", "en", "manipulation", "transitive", ["water", "eggs", "pasta"], "low"),
    VerbEntry("simmer", "en", "manipulation", "transitive", ["sauce", "soup", "stew"], "low"),
    VerbEntry("steam", "en", "manipulation", "transitive", ["vegetables", "rice", "fish"], "low"),
    VerbEntry("blanch", "en", "manipulation", "transitive", ["vegetables", "almonds", "tomatoes"], "low"),
    VerbEntry("braise", "en", "manipulation", "transitive", ["meat", "vegetables"], "low"),
    VerbEntry("poach", "en", "manipulation", "transitive", ["egg", "fish", "fruit"], "low"),
    VerbEntry("marinate", "en", "manipulation", "transitive", ["meat", "vegetables", "tofu"], "low"),
    VerbEntry("season", "en", "manipulation", "transitive", ["food", "pan", "dish"], "low"),
    VerbEntry("taste", "en", "manipulation", "transitive", ["food", "wine", "freedom"], "low"),
    VerbEntry("serve", "en", "manipulation", "transitive", ["food", "customer", "purpose"], "low"),
    VerbEntry("plate", "en", "manipulation", "transitive", ["food", "dish"], "low"),
    VerbEntry("garnish", "en", "manipulation", "transitive", ["dish", "drink"], "low"),
    
    # LOCOMOTION
    VerbEntry("walk", "en", "locomotion", "intransitive", ["distance", "dog", "path"], "high"),
    VerbEntry("run", "en", "locomotion", "intransitive", ["marathon", "errand", "program"], "high"),
    VerbEntry("jog", "en", "locomotion", "intransitive", ["path", "memory"], "high"),
    VerbEntry("sprint", "en", "locomotion", "intransitive", ["finish", "goal"], "high"),
    VerbEntry("climb", "en", "locomotion", "transitive", ["stairs", "ladder", "mountain"], "high"),
    VerbEntry("descend", "en", "locomotion", "transitive", ["stairs", "mountain", "slope"], "medium"),
    VerbEntry("crawl", "en", "locomotion", "intransitive", ["floor", "tunnel", "web"], "high"),
    VerbEntry("crouch", "en", "locomotion", "intransitive", [], "medium"),
    VerbEntry("squat", "en", "locomotion", "intransitive", [], "medium"),
    VerbEntry("kneel", "en", "locomotion", "intransitive", [], "medium"),
    VerbEntry("stand", "en", "locomotion", "intransitive", [], "low"),
    VerbEntry("sit", "en", "locomotion", "intransitive", ["chair", "exam"], "low"),
    VerbEntry("lie", "en", "locomotion", "intransitive", ["bed", "floor"], "low"),
    VerbEntry("lean", "en", "locomotion", "intransitive", ["wall", "rail"], "low"),
    VerbEntry("bend", "en", "locomotion", "intransitive", ["forward", "rules"], "medium"),
    VerbEntry("stretch", "en", "locomotion", "transitive", ["muscles", "truth", "budget"], "medium"),
    VerbEntry("reach", "en", "locomotion", "transitive", ["shelf", "goal", "conclusion"], "medium"),
    VerbEntry("step", "en", "locomotion", "intransitive", ["forward", "aside", "stone"], "low"),
    VerbEntry("hop", "en", "locomotion", "intransitive", ["foot", "fence"], "medium"),
    VerbEntry("jump", "en", "locomotion", "intransitive", ["rope", "conclusion", "queue"], "high"),
    VerbEntry("leap", "en", "locomotion", "intransitive", ["gap", "faith"], "high"),
    VerbEntry("skip", "en", "locomotion", "transitive", ["rope", "chapter", "meal"], "medium"),
    VerbEntry("dance", "en", "locomotion", "intransitive", ["waltz", "ballet"], "high"),
    VerbEntry("swim", "en", "locomotion", "intransitive", ["pool", "lake", "sea"], "high"),
    VerbEntry("dive", "en", "locomotion", "intransitive", ["water", "topic"], "high"),
    VerbEntry("float", "en", "locomotion", "intransitive", ["water", "air"], "low"),
    VerbEntry("paddle", "en", "locomotion", "transitive", ["canoe", "kayak", "feet"], "medium"),
    VerbEntry("row", "en", "locomotion", "transitive", ["boat", "oar"], "high"),
    VerbEntry("cycle", "en", "locomotion", "intransitive", ["bike", "path"], "high"),
    VerbEntry("ride", "en", "locomotion", "transitive", ["bike", "horse", "wave"], "medium"),
    VerbEntry("drive", "en", "locomotion", "transitive", ["car", "nail", "point"], "medium"),
    VerbEntry("steer", "en", "locomotion", "transitive", ["car", "boat", "conversation"], "low"),
    VerbEntry("park", "en", "locomotion", "transitive", ["car", "bike"], "low"),
    VerbEntry("balance", "en", "locomotion", "transitive", ["body", "books", "budget"], "medium"),
    VerbEntry("stumble", "en", "locomotion", "intransitive", ["step", "words"], "medium"),
    VerbEntry("trip", "en", "locomotion", "intransitive", ["wire", "step"], "medium"),
    VerbEntry("fall", "en", "locomotion", "intransitive", ["ground", "asleep", "love"], "high"),
    VerbEntry("roll", "en", "locomotion", "intransitive", ["ground", "hill"], "medium"),
    VerbEntry("tumble", "en", "locomotion", "intransitive", ["ground", "stairs"], "high"),
    VerbEntry("slide", "en", "locomotion", "intransitive", ["ice", "slide"], "low"),
    VerbEntry("glide", "en", "locomotion", "intransitive", ["ice", "air"], "low"),
    VerbEntry("skate", "en", "locomotion", "intransitive", ["ice", "rink"], "medium"),
    VerbEntry("ski", "en", "locomotion", "intransitive", ["mountain", "slope"], "high"),
    
    # PERCEPTION
    VerbEntry("look", "en", "perception", "intransitive", ["direction", "picture", "mirror"], "none"),
    VerbEntry("see", "en", "perception", "transitive", ["object", "movie", "doctor"], "none"),
    VerbEntry("watch", "en", "perception", "transitive", ["TV", "movie", "child"], "none"),
    VerbEntry("observe", "en", "perception", "transitive", ["behavior", "stars", "rules"], "none"),
    VerbEntry("notice", "en", "perception", "transitive", ["change", "detail", "person"], "none"),
    VerbEntry("spot", "en", "perception", "transitive", ["error", "friend", "location"], "none"),
    VerbEntry("gaze", "en", "perception", "intransitive", ["stars", "horizon", "eyes"], "none"),
    VerbEntry("stare", "en", "perception", "intransitive", ["screen", "person", "wall"], "none"),
    VerbEntry("glance", "en", "perception", "intransitive", ["watch", "direction", "paper"], "none"),
    VerbEntry("peek", "en", "perception", "intransitive", ["window", "door", "cards"], "none"),
    VerbEntry("scan", "en", "perception", "transitive", ["room", "document", "horizon"], "none"),
    VerbEntry("examine", "en", "perception", "transitive", ["patient", "evidence", "document"], "none"),
    VerbEntry("inspect", "en", "perception", "transitive", ["vehicle", "work", "damage"], "none"),
    VerbEntry("search", "en", "perception", "transitive", ["room", "web", "answers"], "low"),
    VerbEntry("find", "en", "perception", "transitive", ["keys", "solution", "time"], "low"),
    VerbEntry("discover", "en", "perception", "transitive", ["truth", "place", "talent"], "none"),
    VerbEntry("read", "en", "perception", "transitive", ["book", "sign", "lips"], "none"),
    VerbEntry("listen", "en", "perception", "intransitive", ["music", "advice", "carefully"], "none"),
    VerbEntry("hear", "en", "perception", "transitive", ["sound", "news", "case"], "none"),
    VerbEntry("smell", "en", "perception", "transitive", ["flower", "gas", "trouble"], "none"),
    VerbEntry("sniff", "en", "perception", "transitive", ["air", "food", "drugs"], "low"),
    VerbEntry("taste", "en", "perception", "transitive", ["food", "wine", "success"], "low"),
    VerbEntry("feel", "en", "perception", "transitive", ["texture", "emotion", "pain"], "low"),
    VerbEntry("touch", "en", "perception", "transitive", ["surface", "heart", "base"], "low"),
    VerbEntry("sense", "en", "perception", "transitive", ["danger", "presence", "change"], "none"),
    VerbEntry("detect", "en", "perception", "transitive", ["smell", "error", "movement"], "none"),
    VerbEntry("recognize", "en", "perception", "transitive", ["face", "voice", "achievement"], "none"),
    VerbEntry("identify", "en", "perception", "transitive", ["person", "problem", "species"], "none"),
    
    # COMMUNICATION
    VerbEntry("speak", "en", "communication", "intransitive", ["language", "truth", "volume"], "low"),
    VerbEntry("talk", "en", "communication", "intransitive", ["phone", "sense", "business"], "low"),
    VerbEntry("say", "en", "communication", "transitive", ["words", "goodbye", "prayer"], "low"),
    VerbEntry("tell", "en", "communication", "transitive", ["story", "truth", "joke"], "low"),
    VerbEntry("ask", "en", "communication", "transitive", ["question", "favor", "permission"], "low"),
    VerbEntry("answer", "en", "communication", "transitive", ["question", "phone", "door"], "low"),
    VerbEntry("explain", "en", "communication", "transitive", ["concept", "situation", "rules"], "low"),
    VerbEntry("describe", "en", "communication", "transitive", ["scene", "problem", "person"], "low"),
    VerbEntry("discuss", "en", "communication", "transitive", ["topic", "plans", "options"], "low"),
    VerbEntry("argue", "en", "communication", "intransitive", ["point", "case", "politics"], "low"),
    VerbEntry("debate", "en", "communication", "transitive", ["issue", "motion", "options"], "low"),
    VerbEntry("negotiate", "en", "communication", "transitive", ["deal", "terms", "peace"], "low"),
    VerbEntry("persuade", "en", "communication", "transitive", ["person", "audience", "jury"], "low"),
    VerbEntry("convince", "en", "communication", "transitive", ["person", "audience", "self"], "low"),
    VerbEntry("announce", "en", "communication", "transitive", ["news", "decision", "winner"], "low"),
    VerbEntry("declare", "en", "communication", "transitive", ["war", "bankruptcy", "winner"], "low"),
    VerbEntry("report", "en", "communication", "transitive", ["news", "findings", "crime"], "low"),
    VerbEntry("present", "en", "communication", "transitive", ["findings", "gift", "case"], "low"),
    VerbEntry("lecture", "en", "communication", "intransitive", ["topic", "class", "child"], "low"),
    VerbEntry("teach", "en", "communication", "transitive", ["subject", "skill", "lesson"], "low"),
    VerbEntry("instruct", "en", "communication", "transitive", ["student", "class", "jury"], "low"),
    VerbEntry("demonstrate", "en", "communication", "transitive", ["technique", "product", "concern"], "low"),
    VerbEntry("show", "en", "communication", "transitive", ["picture", "way", "emotion"], "low"),
    VerbEntry("introduce", "en", "communication", "transitive", ["person", "topic", "product"], "low"),
    VerbEntry("greet", "en", "communication", "transitive", ["person", "guest", "day"], "low"),
    VerbEntry("welcome", "en", "communication", "transitive", ["guest", "feedback", "change"], "low"),
    VerbEntry("thank", "en", "communication", "transitive", ["person", "host", "god"], "low"),
    VerbEntry("apologize", "en", "communication", "intransitive", ["mistake", "delay", "behavior"], "low"),
    VerbEntry("compliment", "en", "communication", "transitive", ["person", "work", "outfit"], "low"),
    VerbEntry("criticize", "en", "communication", "transitive", ["work", "decision", "person"], "low"),
    VerbEntry("praise", "en", "communication", "transitive", ["work", "effort", "child"], "low"),
    VerbEntry("encourage", "en", "communication", "transitive", ["person", "behavior", "team"], "low"),
    VerbEntry("warn", "en", "communication", "transitive", ["person", "danger", "consequence"], "low"),
    VerbEntry("advise", "en", "communication", "transitive", ["person", "client", "caution"], "low"),
    VerbEntry("recommend", "en", "communication", "transitive", ["product", "action", "person"], "low"),
    VerbEntry("suggest", "en", "communication", "transitive", ["idea", "option", "name"], "low"),
    VerbEntry("propose", "en", "communication", "transitive", ["idea", "marriage", "toast"], "low"),
    VerbEntry("request", "en", "communication", "transitive", ["help", "information", "meeting"], "low"),
    VerbEntry("order", "en", "communication", "transitive", ["food", "product", "troops"], "low"),
    VerbEntry("command", "en", "communication", "transitive", ["troops", "attention", "respect"], "low"),
    VerbEntry("demand", "en", "communication", "transitive", ["answer", "action", "rights"], "low"),
    VerbEntry("insist", "en", "communication", "intransitive", ["point", "payment", "truth"], "low"),
    VerbEntry("refuse", "en", "communication", "transitive", ["offer", "request", "entry"], "low"),
    VerbEntry("decline", "en", "communication", "transitive", ["offer", "invitation", "comment"], "low"),
    VerbEntry("accept", "en", "communication", "transitive", ["offer", "invitation", "responsibility"], "low"),
    VerbEntry("agree", "en", "communication", "intransitive", ["terms", "proposal", "disagree"], "none"),
    VerbEntry("disagree", "en", "communication", "intransitive", ["point", "decision", "politics"], "none"),
    VerbEntry("promise", "en", "communication", "transitive", ["action", "result", "moon"], "low"),
    VerbEntry("swear", "en", "communication", "transitive", ["oath", "truth", "allegiance"], "low"),
    VerbEntry("confess", "en", "communication", "transitive", ["crime", "love", "sin"], "low"),
    VerbEntry("admit", "en", "communication", "transitive", ["mistake", "guilt", "patient"], "low"),
    VerbEntry("deny", "en", "communication", "transitive", ["accusation", "access", "request"], "low"),
    VerbEntry("lie", "en", "communication", "intransitive", ["truth", "court", "bed"], "low"),
    VerbEntry("whisper", "en", "communication", "transitive", ["secret", "words", "name"], "low"),
    VerbEntry("shout", "en", "communication", "transitive", ["order", "name", "joy"], "medium"),
    VerbEntry("yell", "en", "communication", "transitive", ["warning", "name", "instructions"], "medium"),
    VerbEntry("scream", "en", "communication", "intransitive", ["fear", "joy", "pain"], "medium"),
    VerbEntry("call", "en", "communication", "transitive", ["name", "phone", "meeting"], "low"),
    VerbEntry("signal", "en", "communication", "transitive", ["turn", "help", "intent"], "low"),
    VerbEntry("gesture", "en", "communication", "intransitive", ["direction", "hand", "wildly"], "low"),
    VerbEntry("wave", "en", "communication", "transitive", ["hand", "flag", "goodbye"], "low"),
    VerbEntry("point", "en", "communication", "intransitive", ["direction", "finger", "out"], "low"),
    VerbEntry("nod", "en", "communication", "intransitive", ["agreement", "head", "off"], "low"),
    VerbEntry("shake", "en", "communication", "transitive", ["head", "hand", "dice"], "low"),
    VerbEntry("bow", "en", "communication", "intransitive", ["respect", "pressure", "stage"], "low"),
    VerbEntry("salute", "en", "communication", "transitive", ["flag", "officer", "sun"], "low"),
    VerbEntry("hug", "en", "communication", "transitive", ["person", "tree", "idea"], "medium"),
    VerbEntry("kiss", "en", "communication", "transitive", ["person", "baby", "ring"], "low"),
    VerbEntry("clap", "en", "communication", "intransitive", ["hands", "applause", "back"], "low"),
    VerbEntry("cheer", "en", "communication", "transitive", ["team", "person", "crowd"], "low"),
    VerbEntry("sing", "en", "communication", "transitive", ["song", "praises", "tune"], "low"),
    VerbEntry("hum", "en", "communication", "transitive", ["tune", "song", "melody"], "low"),
    VerbEntry("whistle", "en", "communication", "transitive", ["tune", "taxi", "dog"], "low"),
    
    # COGNITIVE
    VerbEntry("think", "en", "cognitive", "intransitive", ["problem", "carefully", "aloud"], "none"),
    VerbEntry("consider", "en", "cognitive", "transitive", ["option", "request", "feelings"], "none"),
    VerbEntry("contemplate", "en", "cognitive", "transitive", ["future", "action", "navel"], "none"),
    VerbEntry("ponder", "en", "cognitive", "transitive", ["question", "meaning", "options"], "none"),
    VerbEntry("reflect", "en", "cognitive", "intransitive", ["past", "experience", "light"], "none"),
    VerbEntry("meditate", "en", "cognitive", "intransitive", ["quietly", "morning", "yoga"], "low"),
    VerbEntry("focus", "en", "cognitive", "transitive", ["attention", "camera", "efforts"], "none"),
    VerbEntry("concentrate", "en", "cognitive", "intransitive", ["task", "hard", "juice"], "none"),
    VerbEntry("analyze", "en", "cognitive", "transitive", ["data", "situation", "problem"], "none"),
    VerbEntry("evaluate", "en", "cognitive", "transitive", ["performance", "options", "risk"], "none"),
    VerbEntry("assess", "en", "cognitive", "transitive", ["situation", "damage", "value"], "none"),
    VerbEntry("judge", "en", "cognitive", "transitive", ["performance", "case", "character"], "none"),
    VerbEntry("compare", "en", "cognitive", "transitive", ["options", "prices", "notes"], "none"),
    VerbEntry("contrast", "en", "cognitive", "transitive", ["ideas", "colors", "approaches"], "none"),
    VerbEntry("distinguish", "en", "cognitive", "transitive", ["differences", "self", "features"], "none"),
    VerbEntry("differentiate", "en", "cognitive", "transitive", ["products", "self", "cells"], "none"),
    VerbEntry("categorize", "en", "cognitive", "transitive", ["items", "data", "expenses"], "none"),
    VerbEntry("classify", "en", "cognitive", "transitive", ["documents", "species", "information"], "none"),
    VerbEntry("understand", "en", "cognitive", "transitive", ["concept", "language", "feelings"], "none"),
    VerbEntry("comprehend", "en", "cognitive", "transitive", ["text", "situation", "magnitude"], "none"),
    VerbEntry("interpret", "en", "cognitive", "transitive", ["data", "dreams", "law"], "none"),
    VerbEntry("infer", "en", "cognitive", "transitive", ["meaning", "conclusion", "intent"], "none"),
    VerbEntry("deduce", "en", "cognitive", "transitive", ["conclusion", "answer", "identity"], "none"),
    VerbEntry("conclude", "en", "cognitive", "transitive", ["analysis", "meeting", "deal"], "none"),
    VerbEntry("decide", "en", "cognitive", "transitive", ["action", "fate", "case"], "none"),
    VerbEntry("choose", "en", "cognitive", "transitive", ["option", "wisely", "sides"], "none"),
    VerbEntry("select", "en", "cognitive", "transitive", ["option", "team", "winner"], "none"),
    VerbEntry("prefer", "en", "cognitive", "transitive", ["option", "tea", "silence"], "none"),
    VerbEntry("plan", "en", "cognitive", "transitive", ["trip", "strategy", "future"], "none"),
    VerbEntry("strategize", "en", "cognitive", "intransitive", ["carefully", "together", "ahead"], "none"),
    VerbEntry("schedule", "en", "cognitive", "transitive", ["meeting", "appointment", "time"], "none"),
    VerbEntry("organize", "en", "cognitive", "transitive", ["event", "thoughts", "files"], "none"),
    VerbEntry("prioritize", "en", "cognitive", "transitive", ["tasks", "goals", "health"], "none"),
    VerbEntry("estimate", "en", "cognitive", "transitive", ["cost", "time", "distance"], "none"),
    VerbEntry("calculate", "en", "cognitive", "transitive", ["total", "risk", "trajectory"], "none"),
    VerbEntry("compute", "en", "cognitive", "transitive", ["result", "tax", "average"], "none"),
    VerbEntry("solve", "en", "cognitive", "transitive", ["problem", "equation", "mystery"], "none"),
    VerbEntry("figure", "en", "cognitive", "transitive", ["solution", "out", "problem"], "none"),
    VerbEntry("determine", "en", "cognitive", "transitive", ["cause", "outcome", "winner"], "none"),
    VerbEntry("verify", "en", "cognitive", "transitive", ["information", "identity", "claim"], "none"),
    VerbEntry("confirm", "en", "cognitive", "transitive", ["reservation", "appointment", "suspicion"], "none"),
    VerbEntry("validate", "en", "cognitive", "transitive", ["data", "ticket", "feelings"], "none"),
    VerbEntry("remember", "en", "cognitive", "transitive", ["name", "event", "password"], "none"),
    VerbEntry("recall", "en", "cognitive", "transitive", ["memory", "product", "information"], "none"),
    VerbEntry("recollect", "en", "cognitive", "transitive", ["events", "details", "self"], "none"),
    VerbEntry("memorize", "en", "cognitive", "transitive", ["facts", "lines", "numbers"], "none"),
    VerbEntry("forget", "en", "cognitive", "transitive", ["name", "password", "past"], "none"),
    VerbEntry("learn", "en", "cognitive", "transitive", ["skill", "language", "lesson"], "none"),
    VerbEntry("study", "en", "cognitive", "transitive", ["subject", "hard", "behavior"], "none"),
    VerbEntry("research", "en", "cognitive", "transitive", ["topic", "market", "options"], "none"),
    VerbEntry("investigate", "en", "cognitive", "transitive", ["case", "claim", "options"], "none"),
    VerbEntry("explore", "en", "cognitive", "transitive", ["area", "options", "ideas"], "low"),
    VerbEntry("experiment", "en", "cognitive", "intransitive", ["lab", "recipes", "styles"], "low"),
    VerbEntry("test", "en", "cognitive", "transitive", ["hypothesis", "product", "patience"], "low"),
    VerbEntry("hypothesize", "en", "cognitive", "transitive", ["theory", "cause", "outcome"], "none"),
    VerbEntry("theorize", "en", "cognitive", "intransitive", ["about", "cause", "origin"], "none"),
    VerbEntry("speculate", "en", "cognitive", "intransitive", ["market", "outcome", "cause"], "none"),
    VerbEntry("predict", "en", "cognitive", "transitive", ["outcome", "weather", "future"], "none"),
    VerbEntry("forecast", "en", "cognitive", "transitive", ["weather", "sales", "trends"], "none"),
    VerbEntry("anticipate", "en", "cognitive", "transitive", ["problems", "needs", "arrival"], "none"),
    VerbEntry("expect", "en", "cognitive", "transitive", ["result", "delivery", "baby"], "none"),
    VerbEntry("assume", "en", "cognitive", "transitive", ["responsibility", "position", "truth"], "none"),
    VerbEntry("presume", "en", "cognitive", "transitive", ["innocence", "consent", "outcome"], "none"),
    VerbEntry("believe", "en", "cognitive", "transitive", ["story", "theory", "self"], "none"),
    VerbEntry("doubt", "en", "cognitive", "transitive", ["claim", "self", "sincerity"], "none"),
    VerbEntry("question", "en", "cognitive", "transitive", ["authority", "motives", "witness"], "none"),
    VerbEntry("wonder", "en", "cognitive", "intransitive", ["about", "why", "how"], "none"),
    VerbEntry("imagine", "en", "cognitive", "transitive", ["scene", "future", "possibility"], "none"),
    VerbEntry("visualize", "en", "cognitive", "transitive", ["goal", "success", "data"], "none"),
    VerbEntry("dream", "en", "cognitive", "intransitive", ["night", "big", "about"], "none"),
    VerbEntry("fantasize", "en", "cognitive", "intransitive", ["about", "future", "vacation"], "none"),
    VerbEntry("create", "en", "cognitive", "transitive", ["art", "plan", "account"], "low"),
    VerbEntry("design", "en", "cognitive", "transitive", ["product", "system", "logo"], "low"),
    VerbEntry("invent", "en", "cognitive", "transitive", ["device", "excuse", "word"], "low"),
    VerbEntry("innovate", "en", "cognitive", "intransitive", ["constantly", "industry", "solutions"], "low"),
    VerbEntry("compose", "en", "cognitive", "transitive", ["music", "letter", "self"], "low"),
    VerbEntry("formulate", "en", "cognitive", "transitive", ["plan", "theory", "response"], "none"),
    VerbEntry("develop", "en", "cognitive", "transitive", ["skill", "product", "film"], "low"),
    VerbEntry("improve", "en", "cognitive", "transitive", ["skill", "process", "health"], "low"),
    VerbEntry("optimize", "en", "cognitive", "transitive", ["process", "performance", "route"], "none"),
    VerbEntry("simplify", "en", "cognitive", "transitive", ["process", "explanation", "life"], "none"),
    VerbEntry("complicate", "en", "cognitive", "transitive", ["matters", "situation", "things"], "none"),
    VerbEntry("elaborate", "en", "cognitive", "intransitive", ["details", "further", "plan"], "none"),
    
    # SOCIAL / EMOTIONAL
    VerbEntry("help", "en", "social", "transitive", ["person", "cause", "self"], "medium"),
    VerbEntry("assist", "en", "social", "transitive", ["person", "customer", "process"], "medium"),
    VerbEntry("support", "en", "social", "transitive", ["person", "cause", "weight"], "medium"),
    VerbEntry("care", "en", "social", "intransitive", ["patient", "child", "deeply"], "medium"),
    VerbEntry("nurture", "en", "social", "transitive", ["child", "talent", "relationship"], "medium"),
    VerbEntry("comfort", "en", "social", "transitive", ["person", "child", "self"], "low"),
    VerbEntry("console", "en", "social", "transitive", ["person", "friend", "widow"], "low"),
    VerbEntry("encourage", "en", "social", "transitive", ["person", "behavior", "growth"], "low"),
    VerbEntry("motivate", "en", "social", "transitive", ["team", "self", "student"], "low"),
    VerbEntry("inspire", "en", "social", "transitive", ["person", "action", "confidence"], "low"),
    VerbEntry("guide", "en", "social", "transitive", ["person", "tour", "decision"], "low"),
    VerbEntry("lead", "en", "social", "transitive", ["team", "way", "life"], "medium"),
    VerbEntry("follow", "en", "social", "transitive", ["leader", "rules", "path"], "medium"),
    VerbEntry("supervise", "en", "social", "transitive", ["work", "children", "project"], "low"),
    VerbEntry("manage", "en", "social", "transitive", ["team", "project", "time"], "low"),
    VerbEntry("delegate", "en", "social", "transitive", ["task", "authority", "responsibility"], "low"),
    VerbEntry("collaborate", "en", "social", "intransitive", ["project", "team", "closely"], "low"),
    VerbEntry("cooperate", "en", "social", "intransitive", ["investigation", "fully", "project"], "low"),
    VerbEntry("participate", "en", "social", "intransitive", ["event", "discussion", "actively"], "low"),
    VerbEntry("contribute", "en", "social", "intransitive", ["discussion", "cause", "generously"], "low"),
    VerbEntry("share", "en", "social", "transitive", ["food", "information", "responsibility"], "low"),
    VerbEntry("give", "en", "social", "transitive", ["gift", "advice", "time"], "low"),
    VerbEntry("receive", "en", "social", "transitive", ["gift", "news", "treatment"], "low"),
    VerbEntry("donate", "en", "social", "transitive", ["money", "blood", "time"], "low"),
    VerbEntry("lend", "en", "social", "transitive", ["money", "hand", "ear"], "low"),
    VerbEntry("borrow", "en", "social", "transitive", ["money", "book", "idea"], "low"),
    VerbEntry("return", "en", "social", "transitive", ["item", "favor", "home"], "low"),
    VerbEntry("exchange", "en", "social", "transitive", ["gifts", "information", "currency"], "low"),
    VerbEntry("trade", "en", "social", "transitive", ["goods", "stocks", "places"], "low"),
    VerbEntry("buy", "en", "social", "transitive", ["product", "time", "groceries"], "low"),
    VerbEntry("sell", "en", "social", "transitive", ["product", "idea", "house"], "low"),
    VerbEntry("pay", "en", "social", "transitive", ["bill", "attention", "respects"], "low"),
    VerbEntry("rent", "en", "social", "transitive", ["apartment", "car", "equipment"], "low"),
    VerbEntry("hire", "en", "social", "transitive", ["employee", "car", "lawyer"], "low"),
    VerbEntry("fire", "en", "social", "transitive", ["employee", "gun", "imagination"], "low"),
    VerbEntry("employ", "en", "social", "transitive", ["worker", "strategy", "tactic"], "low"),
    VerbEntry("interview", "en", "social", "transitive", ["candidate", "witness", "celebrity"], "low"),
    VerbEntry("meet", "en", "social", "transitive", ["person", "deadline", "needs"], "low"),
    VerbEntry("visit", "en", "social", "transitive", ["person", "place", "website"], "low"),
    VerbEntry("host", "en", "social", "transitive", ["party", "guest", "show"], "low"),
    VerbEntry("invite", "en", "social", "transitive", ["guest", "trouble", "comment"], "low"),
    VerbEntry("entertain", "en", "social", "transitive", ["guest", "idea", "crowd"], "low"),
    VerbEntry("celebrate", "en", "social", "transitive", ["birthday", "victory", "life"], "low"),
    VerbEntry("party", "en", "social", "intransitive", ["night", "hard", "weekend"], "medium"),
    VerbEntry("socialize", "en", "social", "intransitive", ["colleagues", "networking", "pets"], "low"),
    VerbEntry("network", "en", "social", "intransitive", ["event", "professionally", "computers"], "low"),
    VerbEntry("befriend", "en", "social", "transitive", ["person", "neighbor", "stranger"], "low"),
    VerbEntry("date", "en", "social", "transitive", ["person", "document", "artifact"], "low"),
    VerbEntry("marry", "en", "social", "transitive", ["person", "couple", "traditions"], "low"),
    VerbEntry("divorce", "en", "social", "transitive", ["spouse", "reality", "self"], "low"),
    VerbEntry("forgive", "en", "social", "transitive", ["person", "mistake", "debt"], "none"),
    VerbEntry("trust", "en", "social", "transitive", ["person", "process", "instinct"], "none"),
    VerbEntry("respect", "en", "social", "transitive", ["person", "rules", "privacy"], "none"),
    VerbEntry("admire", "en", "social", "transitive", ["person", "view", "courage"], "none"),
    VerbEntry("appreciate", "en", "social", "transitive", ["help", "art", "value"], "none"),
    VerbEntry("love", "en", "social", "transitive", ["person", "food", "life"], "none"),
    VerbEntry("hate", "en", "social", "transitive", ["person", "task", "waiting"], "none"),
    VerbEntry("like", "en", "social", "transitive", ["food", "person", "idea"], "none"),
    VerbEntry("dislike", "en", "social", "transitive", ["food", "person", "idea"], "none"),
    VerbEntry("enjoy", "en", "social", "transitive", ["activity", "meal", "life"], "none"),
    VerbEntry("suffer", "en", "social", "intransitive", ["pain", "loss", "consequences"], "none"),
    VerbEntry("grieve", "en", "social", "intransitive", ["loss", "death", "deeply"], "none"),
    VerbEntry("mourn", "en", "social", "transitive", ["loss", "death", "past"], "none"),
    VerbEntry("worry", "en", "social", "intransitive", ["future", "health", "constantly"], "none"),
    VerbEntry("fear", "en", "social", "transitive", ["failure", "unknown", "worst"], "none"),
    VerbEntry("hope", "en", "social", "intransitive", ["best", "future", "outcome"], "none"),
    VerbEntry("wish", "en", "social", "transitive", ["luck", "success", "well"], "none"),
    VerbEntry("pray", "en", "social", "intransitive", ["god", "success", "peace"], "low"),
    VerbEntry("worship", "en", "social", "transitive", ["god", "celebrity", "ground"], "low"),
    
    # SELF-CARE
    VerbEntry("wash", "en", "self_care", "transitive", ["hands", "face", "dishes"], "medium"),
    VerbEntry("bathe", "en", "self_care", "transitive", ["body", "child", "pet"], "medium"),
    VerbEntry("shower", "en", "self_care", "intransitive", [], "medium"),
    VerbEntry("brush", "en", "self_care", "transitive", ["teeth", "hair", "floor"], "low"),
    VerbEntry("floss", "en", "self_care", "transitive", ["teeth"], "low"),
    VerbEntry("shave", "en", "self_care", "transitive", ["face", "legs", "head"], "low"),
    VerbEntry("trim", "en", "self_care", "transitive", ["nails", "hair", "hedge"], "low"),
    VerbEntry("cut", "en", "self_care", "transitive", ["hair", "nails", "paper"], "low"),
    VerbEntry("style", "en", "self_care", "transitive", ["hair", "outfit", "room"], "low"),
    VerbEntry("apply", "en", "self_care", "transitive", ["makeup", "lotion", "pressure"], "low"),
    VerbEntry("dress", "en", "self_care", "transitive", ["self", "child", "wound"], "medium"),
    VerbEntry("undress", "en", "self_care", "transitive", ["self", "child"], "low"),
    VerbEntry("change", "en", "self_care", "transitive", ["clothes", "diaper", "channel"], "medium"),
    VerbEntry("wear", "en", "self_care", "transitive", ["clothes", "glasses", "smile"], "low"),
    VerbEntry("eat", "en", "self_care", "transitive", ["food", "meal", "breakfast"], "low"),
    VerbEntry("drink", "en", "self_care", "transitive", ["water", "coffee", "alcohol"], "low"),
    VerbEntry("chew", "en", "self_care", "transitive", ["food", "gum", "nails"], "low"),
    VerbEntry("swallow", "en", "self_care", "transitive", ["food", "pill", "pride"], "low"),
    VerbEntry("digest", "en", "self_care", "transitive", ["food", "information", "news"], "none"),
    VerbEntry("sleep", "en", "self_care", "intransitive", [], "low"),
    VerbEntry("nap", "en", "self_care", "intransitive", [], "low"),
    VerbEntry("rest", "en", "self_care", "intransitive", [], "low"),
    VerbEntry("relax", "en", "self_care", "intransitive", [], "low"),
    VerbEntry("wake", "en", "self_care", "intransitive", [], "low"),
    VerbEntry("breathe", "en", "self_care", "intransitive", [], "low"),
    VerbEntry("cough", "en", "self_care", "intransitive", [], "low"),
    VerbEntry("sneeze", "en", "self_care", "intransitive", [], "low"),
    VerbEntry("yawn", "en", "self_care", "intransitive", [], "low"),
    VerbEntry("stretch", "en", "self_care", "intransitive", [], "medium"),
    VerbEntry("exercise", "en", "self_care", "intransitive", [], "high"),
]


# =============================================================================
# ENGLISH SEED NOUNS (Comprehensive, categorized)
# =============================================================================

ENGLISH_NOUNS = [
    # FOOD - Ingredients
    NounEntry("egg", "en", "food", True, ["crack", "beat", "fry", "boil"], {"fragile": True}),
    NounEntry("milk", "en", "food", False, ["pour", "heat", "froth"], {"liquid": True}),
    NounEntry("butter", "en", "food", False, ["spread", "melt", "cut"], {"temperature_sensitive": True}),
    NounEntry("flour", "en", "food", False, ["measure", "sift", "mix"], {"granular": True}),
    NounEntry("sugar", "en", "food", False, ["measure", "sprinkle", "dissolve"], {"granular": True}),
    NounEntry("salt", "en", "food", False, ["sprinkle", "measure", "dissolve"], {"granular": True}),
    NounEntry("pepper", "en", "food", False, ["grind", "sprinkle"], {"granular": True}),
    NounEntry("oil", "en", "food", False, ["pour", "heat", "drizzle"], {"liquid": True}),
    NounEntry("water", "en", "food", False, ["pour", "boil", "drink"], {"liquid": True}),
    NounEntry("rice", "en", "food", False, ["cook", "rinse", "measure"], {"granular": True}),
    NounEntry("pasta", "en", "food", False, ["cook", "boil", "drain"], {}),
    NounEntry("bread", "en", "food", True, ["slice", "toast", "butter"], {}),
    NounEntry("cheese", "en", "food", False, ["grate", "slice", "melt"], {}),
    NounEntry("meat", "en", "food", False, ["cut", "cook", "season"], {}),
    NounEntry("chicken", "en", "food", True, ["cook", "cut", "season"], {}),
    NounEntry("fish", "en", "food", True, ["cook", "fillet", "season"], {"fragile": True}),
    NounEntry("vegetable", "en", "food", True, ["chop", "cook", "wash"], {}),
    NounEntry("fruit", "en", "food", True, ["cut", "peel", "eat"], {}),
    NounEntry("apple", "en", "food", True, ["cut", "peel", "bite"], {}),
    NounEntry("banana", "en", "food", True, ["peel", "slice", "mash"], {}),
    NounEntry("orange", "en", "food", True, ["peel", "squeeze", "slice"], {}),
    NounEntry("lemon", "en", "food", True, ["squeeze", "slice", "zest"], {}),
    NounEntry("tomato", "en", "food", True, ["slice", "chop", "dice"], {"fragile": True}),
    NounEntry("onion", "en", "food", True, ["chop", "slice", "dice"], {}),
    NounEntry("garlic", "en", "food", True, ["mince", "crush", "peel"], {}),
    NounEntry("potato", "en", "food", True, ["peel", "cut", "mash"], {}),
    NounEntry("carrot", "en", "food", True, ["peel", "chop", "grate"], {}),
    NounEntry("lettuce", "en", "food", False, ["wash", "tear", "chop"], {}),
    NounEntry("salad", "en", "food", True, ["toss", "dress", "serve"], {}),
    NounEntry("soup", "en", "food", True, ["stir", "heat", "serve"], {"liquid": True}),
    NounEntry("sauce", "en", "food", True, ["stir", "pour", "simmer"], {"liquid": True}),
    NounEntry("dough", "en", "food", False, ["knead", "roll", "stretch"], {}),
    NounEntry("batter", "en", "food", False, ["mix", "pour", "whisk"], {"liquid": True}),
    NounEntry("cake", "en", "food", True, ["bake", "decorate", "slice"], {"fragile": True}),
    NounEntry("cookie", "en", "food", True, ["bake", "decorate", "eat"], {}),
    NounEntry("pizza", "en", "food", True, ["bake", "slice", "top"], {}),
    NounEntry("sandwich", "en", "food", True, ["make", "cut", "wrap"], {}),
    NounEntry("coffee", "en", "food", False, ["brew", "pour", "drink"], {"liquid": True, "hot": True}),
    NounEntry("tea", "en", "food", False, ["brew", "steep", "pour"], {"liquid": True, "hot": True}),
    NounEntry("juice", "en", "food", False, ["pour", "squeeze", "drink"], {"liquid": True}),
    NounEntry("wine", "en", "food", False, ["pour", "open", "decant"], {"liquid": True}),
    NounEntry("beer", "en", "food", False, ["pour", "open", "drink"], {"liquid": True}),
    NounEntry("ice", "en", "food", False, ["crush", "add", "melt"], {"cold": True}),
    NounEntry("cream", "en", "food", False, ["whip", "pour", "spread"], {}),
    NounEntry("yogurt", "en", "food", False, ["stir", "eat", "mix"], {}),
    NounEntry("honey", "en", "food", False, ["drizzle", "spread", "pour"], {"liquid": True, "sticky": True}),
    NounEntry("jam", "en", "food", False, ["spread", "stir", "open"], {"sticky": True}),
    NounEntry("peanut butter", "en", "food", False, ["spread", "stir", "scoop"], {"sticky": True}),
    NounEntry("cereal", "en", "food", False, ["pour", "eat", "mix"], {"granular": True}),
    NounEntry("oatmeal", "en", "food", False, ["cook", "stir", "serve"], {}),
    NounEntry("noodle", "en", "food", True, ["cook", "stir", "drain"], {}),
    NounEntry("spaghetti", "en", "food", False, ["cook", "twirl", "serve"], {}),
    
    # KITCHEN TOOLS
    NounEntry("knife", "en", "tool", True, ["cut", "sharpen", "hold"], {"sharp": True}),
    NounEntry("fork", "en", "tool", True, ["stab", "hold", "twirl"], {}),
    NounEntry("spoon", "en", "tool", True, ["stir", "scoop", "measure"], {}),
    NounEntry("spatula", "en", "tool", True, ["flip", "scrape", "spread"], {}),
    NounEntry("ladle", "en", "tool", True, ["pour", "scoop", "serve"], {}),
    NounEntry("whisk", "en", "tool", True, ["beat", "stir", "whip"], {}),
    NounEntry("tongs", "en", "tool", True, ["grab", "flip", "serve"], {}),
    NounEntry("peeler", "en", "tool", True, ["peel", "hold", "use"], {"sharp": True}),
    NounEntry("grater", "en", "tool", True, ["grate", "hold", "clean"], {"sharp": True}),
    NounEntry("can opener", "en", "tool", True, ["open", "turn", "attach"], {}),
    NounEntry("bottle opener", "en", "tool", True, ["open", "pry", "hold"], {}),
    NounEntry("corkscrew", "en", "tool", True, ["twist", "pull", "insert"], {}),
    NounEntry("rolling pin", "en", "tool", True, ["roll", "flatten", "press"], {}),
    NounEntry("cutting board", "en", "tool", True, ["place", "clean", "use"], {}),
    NounEntry("pot", "en", "tool", True, ["fill", "heat", "stir"], {"hot": True}),
    NounEntry("pan", "en", "tool", True, ["heat", "flip", "fry"], {"hot": True}),
    NounEntry("wok", "en", "tool", True, ["stir", "toss", "heat"], {"hot": True}),
    NounEntry("baking sheet", "en", "tool", True, ["place", "grease", "use"], {}),
    NounEntry("mixing bowl", "en", "tool", True, ["fill", "mix", "hold"], {}),
    NounEntry("measuring cup", "en", "tool", True, ["fill", "pour", "measure"], {}),
    NounEntry("measuring spoon", "en", "tool", True, ["scoop", "level", "measure"], {}),
    NounEntry("colander", "en", "tool", True, ["drain", "rinse", "hold"], {}),
    NounEntry("strainer", "en", "tool", True, ["strain", "sift", "hold"], {}),
    NounEntry("blender", "en", "appliance", True, ["blend", "puree", "mix"], {"electrical": True}),
    NounEntry("food processor", "en", "appliance", True, ["chop", "blend", "mix"], {"electrical": True}),
    NounEntry("mixer", "en", "appliance", True, ["mix", "beat", "whip"], {"electrical": True}),
    NounEntry("toaster", "en", "appliance", True, ["toast", "heat", "use"], {"electrical": True}),
    NounEntry("microwave", "en", "appliance", True, ["heat", "defrost", "cook"], {"electrical": True}),
    NounEntry("oven", "en", "appliance", True, ["bake", "roast", "preheat"], {"hot": True, "electrical": True}),
    NounEntry("stove", "en", "appliance", True, ["heat", "cook", "boil"], {"hot": True}),
    NounEntry("refrigerator", "en", "appliance", True, ["store", "cool", "open"], {"electrical": True, "cold": True}),
    NounEntry("freezer", "en", "appliance", True, ["freeze", "store", "open"], {"electrical": True, "cold": True}),
    NounEntry("dishwasher", "en", "appliance", True, ["load", "run", "unload"], {"electrical": True}),
    NounEntry("kettle", "en", "appliance", True, ["boil", "fill", "pour"], {"hot": True}),
    NounEntry("coffee maker", "en", "appliance", True, ["brew", "fill", "clean"], {"electrical": True}),
    
    # HOUSEHOLD ITEMS
    NounEntry("plate", "en", "container", True, ["place", "wash", "stack"], {"fragile": True}),
    NounEntry("bowl", "en", "container", True, ["fill", "wash", "hold"], {"fragile": True}),
    NounEntry("cup", "en", "container", True, ["fill", "drink", "wash"], {"fragile": True}),
    NounEntry("mug", "en", "container", True, ["fill", "drink", "hold"], {}),
    NounEntry("glass", "en", "container", True, ["fill", "pour", "wash"], {"fragile": True}),
    NounEntry("bottle", "en", "container", True, ["fill", "open", "pour"], {}),
    NounEntry("jar", "en", "container", True, ["open", "fill", "seal"], {}),
    NounEntry("container", "en", "container", True, ["fill", "seal", "stack"], {}),
    NounEntry("box", "en", "container", True, ["open", "pack", "tape"], {}),
    NounEntry("bag", "en", "container", True, ["fill", "carry", "open"], {}),
    NounEntry("basket", "en", "container", True, ["fill", "carry", "weave"], {}),
    NounEntry("tray", "en", "container", True, ["carry", "place", "balance"], {}),
    NounEntry("bucket", "en", "container", True, ["fill", "carry", "pour"], {}),
    NounEntry("trash can", "en", "container", True, ["empty", "fill", "line"], {}),
    NounEntry("recycling bin", "en", "container", True, ["fill", "empty", "sort"], {}),
    
    # CLEANING TOOLS
    NounEntry("broom", "en", "tool", True, ["sweep", "hold", "store"], {}),
    NounEntry("dustpan", "en", "tool", True, ["hold", "scoop", "empty"], {}),
    NounEntry("mop", "en", "tool", True, ["mop", "wring", "rinse"], {}),
    NounEntry("vacuum", "en", "appliance", True, ["vacuum", "empty", "push"], {"electrical": True}),
    NounEntry("sponge", "en", "tool", True, ["scrub", "squeeze", "rinse"], {}),
    NounEntry("brush", "en", "tool", True, ["scrub", "sweep", "brush"], {}),
    NounEntry("cloth", "en", "tool", True, ["wipe", "fold", "rinse"], {}),
    NounEntry("rag", "en", "tool", True, ["wipe", "scrub", "wring"], {}),
    NounEntry("towel", "en", "tool", True, ["dry", "fold", "hang"], {}),
    NounEntry("paper towel", "en", "tool", True, ["wipe", "tear", "throw"], {}),
    NounEntry("detergent", "en", "material", False, ["pour", "measure", "add"], {"liquid": True}),
    NounEntry("soap", "en", "material", True, ["lather", "apply", "rinse"], {}),
    NounEntry("bleach", "en", "material", False, ["pour", "dilute", "apply"], {"liquid": True, "hazardous": True}),
    NounEntry("disinfectant", "en", "material", True, ["spray", "wipe", "apply"], {"hazardous": True}),
    
    # FURNITURE
    NounEntry("chair", "en", "furniture", True, ["sit", "move", "push"], {"heavy": True}),
    NounEntry("table", "en", "furniture", True, ["set", "clean", "move"], {"heavy": True}),
    NounEntry("desk", "en", "furniture", True, ["sit at", "organize", "clean"], {"heavy": True}),
    NounEntry("bed", "en", "furniture", True, ["make", "sleep", "move"], {"heavy": True}),
    NounEntry("couch", "en", "furniture", True, ["sit", "move", "vacuum"], {"heavy": True}),
    NounEntry("sofa", "en", "furniture", True, ["sit", "move", "clean"], {"heavy": True}),
    NounEntry("shelf", "en", "furniture", True, ["mount", "organize", "dust"], {}),
    NounEntry("cabinet", "en", "furniture", True, ["open", "organize", "close"], {}),
    NounEntry("drawer", "en", "furniture", True, ["open", "organize", "close"], {}),
    NounEntry("closet", "en", "furniture", True, ["organize", "open", "clean"], {}),
    NounEntry("wardrobe", "en", "furniture", True, ["organize", "open", "move"], {"heavy": True}),
    NounEntry("dresser", "en", "furniture", True, ["organize", "dust", "move"], {"heavy": True}),
    NounEntry("nightstand", "en", "furniture", True, ["place", "organize", "dust"], {}),
    NounEntry("bookshelf", "en", "furniture", True, ["organize", "dust", "mount"], {}),
    NounEntry("mirror", "en", "furniture", True, ["hang", "clean", "look"], {"fragile": True}),
    NounEntry("lamp", "en", "furniture", True, ["turn on", "move", "dust"], {"electrical": True, "fragile": True}),
    NounEntry("rug", "en", "furniture", True, ["vacuum", "roll", "place"], {}),
    NounEntry("carpet", "en", "furniture", False, ["vacuum", "clean", "install"], {}),
    NounEntry("curtain", "en", "furniture", True, ["hang", "open", "close"], {}),
    NounEntry("blind", "en", "furniture", True, ["open", "close", "adjust"], {}),
    
    # CLOTHING
    NounEntry("shirt", "en", "clothing", True, ["wear", "iron", "fold"], {}),
    NounEntry("pants", "en", "clothing", True, ["wear", "fold", "hang"], {}),
    NounEntry("jeans", "en", "clothing", True, ["wear", "fold", "wash"], {}),
    NounEntry("shorts", "en", "clothing", True, ["wear", "fold", "wash"], {}),
    NounEntry("skirt", "en", "clothing", True, ["wear", "hang", "iron"], {}),
    NounEntry("dress", "en", "clothing", True, ["wear", "hang", "iron"], {}),
    NounEntry("suit", "en", "clothing", True, ["wear", "hang", "dry clean"], {}),
    NounEntry("jacket", "en", "clothing", True, ["wear", "hang", "zip"], {}),
    NounEntry("coat", "en", "clothing", True, ["wear", "hang", "button"], {}),
    NounEntry("sweater", "en", "clothing", True, ["wear", "fold", "wash"], {}),
    NounEntry("hoodie", "en", "clothing", True, ["wear", "zip", "wash"], {}),
    NounEntry("t-shirt", "en", "clothing", True, ["wear", "fold", "wash"], {}),
    NounEntry("underwear", "en", "clothing", True, ["wear", "fold", "wash"], {}),
    NounEntry("socks", "en", "clothing", True, ["wear", "fold", "match"], {}),
    NounEntry("shoes", "en", "clothing", True, ["wear", "tie", "polish"], {}),
    NounEntry("boots", "en", "clothing", True, ["wear", "lace", "polish"], {}),
    NounEntry("sandals", "en", "clothing", True, ["wear", "buckle", "slip on"], {}),
    NounEntry("slippers", "en", "clothing", True, ["wear", "slip on", "wash"], {}),
    NounEntry("hat", "en", "clothing", True, ["wear", "adjust", "hang"], {}),
    NounEntry("cap", "en", "clothing", True, ["wear", "adjust", "wash"], {}),
    NounEntry("scarf", "en", "clothing", True, ["wear", "wrap", "tie"], {}),
    NounEntry("gloves", "en", "clothing", True, ["wear", "put on", "remove"], {}),
    NounEntry("belt", "en", "clothing", True, ["wear", "buckle", "tighten"], {}),
    NounEntry("tie", "en", "clothing", True, ["wear", "tie", "loosen"], {}),
    NounEntry("watch", "en", "accessory", True, ["wear", "check", "wind"], {}),
    NounEntry("glasses", "en", "accessory", True, ["wear", "clean", "adjust"], {"fragile": True}),
    NounEntry("sunglasses", "en", "accessory", True, ["wear", "clean", "fold"], {}),
    NounEntry("jewelry", "en", "accessory", False, ["wear", "clean", "store"], {}),
    NounEntry("ring", "en", "accessory", True, ["wear", "put on", "remove"], {}),
    NounEntry("necklace", "en", "accessory", True, ["wear", "clasp", "store"], {}),
    NounEntry("earring", "en", "accessory", True, ["wear", "put on", "remove"], {}),
    NounEntry("bracelet", "en", "accessory", True, ["wear", "clasp", "remove"], {}),
    
    # PERSONAL CARE
    NounEntry("toothbrush", "en", "personal_care", True, ["brush", "rinse", "store"], {}),
    NounEntry("toothpaste", "en", "personal_care", False, ["squeeze", "apply", "cap"], {}),
    NounEntry("dental floss", "en", "personal_care", False, ["pull", "use", "cut"], {}),
    NounEntry("mouthwash", "en", "personal_care", False, ["pour", "gargle", "spit"], {"liquid": True}),
    NounEntry("shampoo", "en", "personal_care", False, ["apply", "lather", "rinse"], {"liquid": True}),
    NounEntry("conditioner", "en", "personal_care", False, ["apply", "massage", "rinse"], {"liquid": True}),
    NounEntry("body wash", "en", "personal_care", False, ["apply", "lather", "rinse"], {"liquid": True}),
    NounEntry("soap", "en", "personal_care", True, ["lather", "rinse", "store"], {}),
    NounEntry("lotion", "en", "personal_care", False, ["apply", "rub", "squeeze"], {"liquid": True}),
    NounEntry("sunscreen", "en", "personal_care", False, ["apply", "rub", "reapply"], {}),
    NounEntry("deodorant", "en", "personal_care", True, ["apply", "roll", "spray"], {}),
    NounEntry("razor", "en", "personal_care", True, ["shave", "rinse", "store"], {"sharp": True}),
    NounEntry("shaving cream", "en", "personal_care", False, ["apply", "lather", "rinse"], {}),
    NounEntry("hairbrush", "en", "personal_care", True, ["brush", "clean", "store"], {}),
    NounEntry("comb", "en", "personal_care", True, ["comb", "style", "clean"], {}),
    NounEntry("hair dryer", "en", "personal_care", True, ["dry", "style", "plug in"], {"electrical": True, "hot": True}),
    NounEntry("curling iron", "en", "personal_care", True, ["curl", "heat", "style"], {"electrical": True, "hot": True}),
    NounEntry("straightener", "en", "personal_care", True, ["straighten", "heat", "style"], {"electrical": True, "hot": True}),
    NounEntry("nail clipper", "en", "personal_care", True, ["clip", "trim", "clean"], {"sharp": True}),
    NounEntry("nail file", "en", "personal_care", True, ["file", "shape", "smooth"], {}),
    NounEntry("tweezers", "en", "personal_care", True, ["pluck", "hold", "grab"], {}),
    NounEntry("cotton ball", "en", "personal_care", True, ["apply", "dab", "remove"], {}),
    NounEntry("cotton swab", "en", "personal_care", True, ["clean", "apply", "dab"], {}),
    NounEntry("tissue", "en", "personal_care", True, ["blow", "wipe", "throw"], {}),
    NounEntry("toilet paper", "en", "personal_care", False, ["use", "tear", "replace"], {}),
    NounEntry("towel", "en", "personal_care", True, ["dry", "wrap", "hang"], {}),
    NounEntry("bathrobe", "en", "personal_care", True, ["wear", "tie", "hang"], {}),
    NounEntry("makeup", "en", "personal_care", False, ["apply", "blend", "remove"], {}),
    NounEntry("lipstick", "en", "personal_care", True, ["apply", "blot", "cap"], {}),
    NounEntry("mascara", "en", "personal_care", True, ["apply", "brush", "remove"], {}),
    NounEntry("foundation", "en", "personal_care", False, ["apply", "blend", "set"], {}),
    NounEntry("perfume", "en", "personal_care", False, ["spray", "apply", "dab"], {"liquid": True}),
    NounEntry("cologne", "en", "personal_care", False, ["spray", "apply", "dab"], {"liquid": True}),
    
    # BABY CARE
    NounEntry("diaper", "en", "baby_care", True, ["change", "fasten", "dispose"], {}),
    NounEntry("baby bottle", "en", "baby_care", True, ["fill", "warm", "feed"], {}),
    NounEntry("pacifier", "en", "baby_care", True, ["give", "clean", "find"], {}),
    NounEntry("baby food", "en", "baby_care", False, ["feed", "warm", "prepare"], {}),
    NounEntry("stroller", "en", "baby_care", True, ["push", "fold", "steer"], {}),
    NounEntry("car seat", "en", "baby_care", True, ["install", "buckle", "adjust"], {}),
    NounEntry("crib", "en", "baby_care", True, ["assemble", "place", "lower"], {}),
    NounEntry("high chair", "en", "baby_care", True, ["place", "clean", "adjust"], {}),
    NounEntry("baby monitor", "en", "baby_care", True, ["turn on", "check", "charge"], {"electrical": True}),
    NounEntry("teething ring", "en", "baby_care", True, ["give", "freeze", "clean"], {}),
    NounEntry("baby wipe", "en", "baby_care", True, ["pull", "wipe", "dispose"], {}),
    NounEntry("baby powder", "en", "baby_care", False, ["apply", "sprinkle", "shake"], {}),
    NounEntry("baby lotion", "en", "baby_care", False, ["apply", "rub", "squeeze"], {"liquid": True}),
    NounEntry("baby shampoo", "en", "baby_care", False, ["apply", "lather", "rinse"], {"liquid": True}),
    NounEntry("bib", "en", "baby_care", True, ["put on", "fasten", "remove"], {}),
    NounEntry("onesie", "en", "baby_care", True, ["dress", "snap", "remove"], {}),
    
    # MEDICAL
    NounEntry("bandage", "en", "medical", True, ["apply", "wrap", "remove"], {}),
    NounEntry("band-aid", "en", "medical", True, ["apply", "peel", "remove"], {}),
    NounEntry("gauze", "en", "medical", False, ["apply", "wrap", "cut"], {}),
    NounEntry("tape", "en", "medical", False, ["apply", "cut", "secure"], {}),
    NounEntry("antiseptic", "en", "medical", False, ["apply", "pour", "spray"], {"liquid": True}),
    NounEntry("thermometer", "en", "medical", True, ["insert", "read", "clean"], {}),
    NounEntry("blood pressure monitor", "en", "medical", True, ["wrap", "inflate", "read"], {"electrical": True}),
    NounEntry("stethoscope", "en", "medical", True, ["place", "listen", "hang"], {}),
    NounEntry("syringe", "en", "medical", True, ["fill", "inject", "dispose"], {"sharp": True}),
    NounEntry("needle", "en", "medical", True, ["insert", "inject", "dispose"], {"sharp": True}),
    NounEntry("pill", "en", "medical", True, ["swallow", "take", "crush"], {}),
    NounEntry("tablet", "en", "medical", True, ["swallow", "dissolve", "take"], {}),
    NounEntry("capsule", "en", "medical", True, ["swallow", "open", "take"], {}),
    NounEntry("medicine", "en", "medical", False, ["take", "measure", "store"], {}),
    NounEntry("prescription", "en", "medical", True, ["fill", "read", "follow"], {}),
    NounEntry("inhaler", "en", "medical", True, ["shake", "inhale", "press"], {}),
    NounEntry("crutch", "en", "medical", True, ["use", "adjust", "lean"], {}),
    NounEntry("wheelchair", "en", "medical", True, ["push", "sit", "fold"], {}),
    NounEntry("walker", "en", "medical", True, ["use", "push", "fold"], {}),
    NounEntry("cane", "en", "medical", True, ["hold", "walk", "lean"], {}),
    NounEntry("eye drops", "en", "medical", True, ["apply", "squeeze", "tilt"], {"liquid": True}),
    NounEntry("ear drops", "en", "medical", True, ["apply", "squeeze", "tilt"], {"liquid": True}),
    NounEntry("ointment", "en", "medical", False, ["apply", "rub", "squeeze"], {}),
    NounEntry("cream", "en", "medical", False, ["apply", "rub", "squeeze"], {}),
    NounEntry("ice pack", "en", "medical", True, ["apply", "freeze", "wrap"], {"cold": True}),
    NounEntry("heating pad", "en", "medical", True, ["apply", "plug in", "adjust"], {"electrical": True, "hot": True}),
    
    # OFFICE/WORK
    NounEntry("computer", "en", "electronics", True, ["use", "turn on", "type"], {"electrical": True}),
    NounEntry("laptop", "en", "electronics", True, ["open", "type", "charge"], {"electrical": True}),
    NounEntry("keyboard", "en", "electronics", True, ["type", "clean", "connect"], {"electrical": True}),
    NounEntry("mouse", "en", "electronics", True, ["click", "move", "scroll"], {"electrical": True}),
    NounEntry("monitor", "en", "electronics", True, ["turn on", "adjust", "clean"], {"electrical": True}),
    NounEntry("printer", "en", "electronics", True, ["print", "load", "connect"], {"electrical": True}),
    NounEntry("scanner", "en", "electronics", True, ["scan", "place", "connect"], {"electrical": True}),
    NounEntry("phone", "en", "electronics", True, ["call", "answer", "charge"], {"electrical": True}),
    NounEntry("tablet", "en", "electronics", True, ["tap", "swipe", "charge"], {"electrical": True}),
    NounEntry("headphones", "en", "electronics", True, ["wear", "connect", "adjust"], {"electrical": True}),
    NounEntry("speaker", "en", "electronics", True, ["turn on", "connect", "adjust"], {"electrical": True}),
    NounEntry("camera", "en", "electronics", True, ["photograph", "focus", "charge"], {"electrical": True}),
    NounEntry("charger", "en", "electronics", True, ["plug in", "connect", "coil"], {"electrical": True}),
    NounEntry("cable", "en", "electronics", True, ["connect", "plug", "coil"], {}),
    NounEntry("battery", "en", "electronics", True, ["insert", "charge", "replace"], {"electrical": True}),
    NounEntry("pen", "en", "office", True, ["write", "cap", "hold"], {}),
    NounEntry("pencil", "en", "office", True, ["write", "sharpen", "erase"], {}),
    NounEntry("marker", "en", "office", True, ["write", "cap", "highlight"], {}),
    NounEntry("highlighter", "en", "office", True, ["highlight", "cap", "mark"], {}),
    NounEntry("eraser", "en", "office", True, ["erase", "rub", "blow"], {}),
    NounEntry("ruler", "en", "office", True, ["measure", "draw", "hold"], {}),
    NounEntry("scissors", "en", "office", True, ["cut", "open", "hold"], {"sharp": True}),
    NounEntry("stapler", "en", "office", True, ["staple", "load", "press"], {}),
    NounEntry("tape", "en", "office", False, ["tape", "cut", "dispense"], {}),
    NounEntry("glue", "en", "office", False, ["apply", "squeeze", "spread"], {"sticky": True}),
    NounEntry("paper", "en", "office", False, ["write", "fold", "cut"], {}),
    NounEntry("notebook", "en", "office", True, ["write", "open", "flip"], {}),
    NounEntry("folder", "en", "office", True, ["file", "label", "organize"], {}),
    NounEntry("binder", "en", "office", True, ["open", "organize", "file"], {}),
    NounEntry("envelope", "en", "office", True, ["seal", "address", "open"], {}),
    NounEntry("stamp", "en", "office", True, ["lick", "stick", "stamp"], {}),
    NounEntry("calendar", "en", "office", True, ["check", "mark", "hang"], {}),
    NounEntry("clock", "en", "office", True, ["check", "set", "hang"], {}),
    NounEntry("whiteboard", "en", "office", True, ["write", "erase", "mount"], {}),
    NounEntry("bulletin board", "en", "office", True, ["pin", "post", "mount"], {}),
    
    # TOOLS (General)
    NounEntry("hammer", "en", "tool", True, ["hammer", "hold", "swing"], {}),
    NounEntry("screwdriver", "en", "tool", True, ["turn", "hold", "insert"], {}),
    NounEntry("wrench", "en", "tool", True, ["turn", "hold", "tighten"], {}),
    NounEntry("pliers", "en", "tool", True, ["grip", "twist", "cut"], {}),
    NounEntry("drill", "en", "tool", True, ["drill", "hold", "charge"], {"electrical": True}),
    NounEntry("saw", "en", "tool", True, ["cut", "hold", "push"], {"sharp": True}),
    NounEntry("level", "en", "tool", True, ["place", "check", "adjust"], {}),
    NounEntry("tape measure", "en", "tool", True, ["measure", "extend", "retract"], {}),
    NounEntry("ladder", "en", "tool", True, ["climb", "place", "fold"], {}),
    NounEntry("flashlight", "en", "tool", True, ["shine", "hold", "turn on"], {"electrical": True}),
    NounEntry("rope", "en", "tool", False, ["tie", "pull", "coil"], {}),
    NounEntry("chain", "en", "tool", True, ["lock", "attach", "pull"], {}),
    NounEntry("lock", "en", "tool", True, ["lock", "unlock", "attach"], {}),
    NounEntry("key", "en", "tool", True, ["turn", "insert", "carry"], {}),
    NounEntry("nail", "en", "tool", True, ["hammer", "pull", "hold"], {"sharp": True}),
    NounEntry("screw", "en", "tool", True, ["turn", "insert", "tighten"], {}),
    NounEntry("bolt", "en", "tool", True, ["tighten", "insert", "remove"], {}),
    NounEntry("nut", "en", "tool", True, ["tighten", "thread", "remove"], {}),
    NounEntry("washer", "en", "tool", True, ["place", "stack", "use"], {}),
    NounEntry("sandpaper", "en", "tool", False, ["sand", "rub", "fold"], {}),
    NounEntry("paint", "en", "material", False, ["apply", "stir", "pour"], {"liquid": True}),
    NounEntry("paintbrush", "en", "tool", True, ["dip", "stroke", "clean"], {}),
    NounEntry("roller", "en", "tool", True, ["roll", "dip", "apply"], {}),
    NounEntry("gloves", "en", "tool", True, ["wear", "remove", "put on"], {}),
    NounEntry("goggles", "en", "tool", True, ["wear", "adjust", "clean"], {}),
    NounEntry("mask", "en", "tool", True, ["wear", "adjust", "remove"], {}),
    NounEntry("helmet", "en", "tool", True, ["wear", "adjust", "remove"], {}),
    
    # GARDEN/OUTDOOR
    NounEntry("shovel", "en", "tool", True, ["dig", "scoop", "lift"], {}),
    NounEntry("rake", "en", "tool", True, ["rake", "gather", "spread"], {}),
    NounEntry("hoe", "en", "tool", True, ["dig", "chop", "weed"], {}),
    NounEntry("pruner", "en", "tool", True, ["cut", "trim", "prune"], {"sharp": True}),
    NounEntry("shears", "en", "tool", True, ["cut", "trim", "clip"], {"sharp": True}),
    NounEntry("lawn mower", "en", "tool", True, ["mow", "push", "start"], {"electrical": True}),
    NounEntry("hose", "en", "tool", True, ["water", "spray", "coil"], {}),
    NounEntry("sprinkler", "en", "tool", True, ["set up", "adjust", "turn on"], {}),
    NounEntry("watering can", "en", "tool", True, ["water", "fill", "pour"], {}),
    NounEntry("wheelbarrow", "en", "tool", True, ["push", "load", "dump"], {}),
    NounEntry("pot", "en", "container", True, ["fill", "plant", "water"], {}),
    NounEntry("planter", "en", "container", True, ["fill", "plant", "arrange"], {}),
    NounEntry("seed", "en", "nature", True, ["plant", "water", "sow"], {}),
    NounEntry("plant", "en", "nature", True, ["water", "prune", "repot"], {}),
    NounEntry("flower", "en", "nature", True, ["pick", "arrange", "water"], {"fragile": True}),
    NounEntry("tree", "en", "nature", True, ["plant", "prune", "climb"], {}),
    NounEntry("bush", "en", "nature", True, ["trim", "plant", "prune"], {}),
    NounEntry("grass", "en", "nature", False, ["mow", "water", "plant"], {}),
    NounEntry("weed", "en", "nature", True, ["pull", "spray", "dig"], {}),
    NounEntry("soil", "en", "nature", False, ["dig", "add", "mix"], {}),
    NounEntry("fertilizer", "en", "material", False, ["spread", "mix", "apply"], {}),
    NounEntry("mulch", "en", "material", False, ["spread", "apply", "layer"], {}),
    NounEntry("compost", "en", "material", False, ["add", "turn", "spread"], {}),
    
    # VEHICLES
    NounEntry("car", "en", "vehicle", True, ["drive", "park", "wash"], {}),
    NounEntry("truck", "en", "vehicle", True, ["drive", "load", "park"], {}),
    NounEntry("van", "en", "vehicle", True, ["drive", "load", "park"], {}),
    NounEntry("motorcycle", "en", "vehicle", True, ["ride", "start", "park"], {}),
    NounEntry("bicycle", "en", "vehicle", True, ["ride", "pedal", "park"], {}),
    NounEntry("scooter", "en", "vehicle", True, ["ride", "push", "park"], {}),
    NounEntry("bus", "en", "vehicle", True, ["board", "ride", "exit"], {}),
    NounEntry("train", "en", "vehicle", True, ["board", "ride", "exit"], {}),
    NounEntry("plane", "en", "vehicle", True, ["board", "fly", "land"], {}),
    NounEntry("boat", "en", "vehicle", True, ["row", "steer", "dock"], {}),
    NounEntry("tire", "en", "vehicle_part", True, ["change", "inflate", "rotate"], {}),
    NounEntry("wheel", "en", "vehicle_part", True, ["turn", "spin", "replace"], {}),
    NounEntry("steering wheel", "en", "vehicle_part", True, ["turn", "hold", "adjust"], {}),
    NounEntry("brake", "en", "vehicle_part", True, ["press", "release", "check"], {}),
    NounEntry("accelerator", "en", "vehicle_part", True, ["press", "release", "push"], {}),
    NounEntry("gear", "en", "vehicle_part", True, ["shift", "change", "engage"], {}),
    NounEntry("seatbelt", "en", "vehicle_part", True, ["fasten", "unbuckle", "adjust"], {}),
    NounEntry("mirror", "en", "vehicle_part", True, ["adjust", "check", "clean"], {}),
    NounEntry("headlight", "en", "vehicle_part", True, ["turn on", "adjust", "clean"], {}),
    NounEntry("windshield", "en", "vehicle_part", True, ["clean", "wipe", "replace"], {}),
    NounEntry("wiper", "en", "vehicle_part", True, ["turn on", "replace", "adjust"], {}),
    NounEntry("horn", "en", "vehicle_part", True, ["honk", "press", "use"], {}),
    NounEntry("door", "en", "vehicle_part", True, ["open", "close", "lock"], {}),
    NounEntry("trunk", "en", "vehicle_part", True, ["open", "close", "load"], {}),
    NounEntry("hood", "en", "vehicle_part", True, ["open", "close", "prop"], {}),
    NounEntry("gas tank", "en", "vehicle_part", True, ["fill", "open", "close"], {}),
    NounEntry("engine", "en", "vehicle_part", True, ["start", "check", "repair"], {}),
    
    # SPORTS/FITNESS
    NounEntry("ball", "en", "sports", True, ["throw", "catch", "kick"], {}),
    NounEntry("bat", "en", "sports", True, ["swing", "hold", "hit"], {}),
    NounEntry("racket", "en", "sports", True, ["swing", "hold", "hit"], {}),
    NounEntry("club", "en", "sports", True, ["swing", "hold", "grip"], {}),
    NounEntry("net", "en", "sports", True, ["set up", "hang", "hit"], {}),
    NounEntry("goal", "en", "sports", True, ["score", "defend", "set up"], {}),
    NounEntry("hoop", "en", "sports", True, ["shoot", "hang", "dunk"], {}),
    NounEntry("weight", "en", "sports", True, ["lift", "curl", "press"], {"heavy": True}),
    NounEntry("dumbbell", "en", "sports", True, ["lift", "curl", "press"], {"heavy": True}),
    NounEntry("barbell", "en", "sports", True, ["lift", "press", "squat"], {"heavy": True}),
    NounEntry("treadmill", "en", "sports", True, ["run", "walk", "set"], {"electrical": True}),
    NounEntry("exercise bike", "en", "sports", True, ["pedal", "adjust", "ride"], {"electrical": True}),
    NounEntry("yoga mat", "en", "sports", True, ["roll", "place", "stretch"], {}),
    NounEntry("jump rope", "en", "sports", True, ["jump", "swing", "skip"], {}),
    NounEntry("resistance band", "en", "sports", True, ["stretch", "pull", "hold"], {}),
    NounEntry("helmet", "en", "sports", True, ["wear", "adjust", "fasten"], {}),
    NounEntry("pads", "en", "sports", True, ["wear", "adjust", "fasten"], {}),
    NounEntry("cleats", "en", "sports", True, ["wear", "lace", "clean"], {}),
    NounEntry("goggles", "en", "sports", True, ["wear", "adjust", "clean"], {}),
    NounEntry("swimsuit", "en", "sports", True, ["wear", "put on", "rinse"], {}),
    NounEntry("towel", "en", "sports", True, ["dry", "wrap", "wipe"], {}),
    NounEntry("water bottle", "en", "sports", True, ["drink", "fill", "squeeze"], {}),
    
    # ENTERTAINMENT/LEISURE
    NounEntry("book", "en", "entertainment", True, ["read", "open", "close"], {}),
    NounEntry("magazine", "en", "entertainment", True, ["read", "flip", "browse"], {}),
    NounEntry("newspaper", "en", "entertainment", True, ["read", "fold", "recycle"], {}),
    NounEntry("TV", "en", "entertainment", True, ["watch", "turn on", "change"], {"electrical": True}),
    NounEntry("remote", "en", "entertainment", True, ["press", "point", "change"], {"electrical": True}),
    NounEntry("game console", "en", "entertainment", True, ["play", "turn on", "connect"], {"electrical": True}),
    NounEntry("controller", "en", "entertainment", True, ["hold", "press", "charge"], {"electrical": True}),
    NounEntry("board game", "en", "entertainment", True, ["play", "set up", "pack"], {}),
    NounEntry("puzzle", "en", "entertainment", True, ["solve", "assemble", "piece"], {}),
    NounEntry("card", "en", "entertainment", True, ["shuffle", "deal", "play"], {}),
    NounEntry("dice", "en", "entertainment", True, ["roll", "throw", "shake"], {}),
    NounEntry("toy", "en", "entertainment", True, ["play", "pick up", "share"], {}),
    NounEntry("doll", "en", "entertainment", True, ["dress", "play", "hold"], {}),
    NounEntry("stuffed animal", "en", "entertainment", True, ["hug", "hold", "wash"], {}),
    NounEntry("blocks", "en", "entertainment", True, ["stack", "build", "knock"], {}),
    NounEntry("Lego", "en", "entertainment", False, ["build", "connect", "snap"], {}),
    NounEntry("crayon", "en", "entertainment", True, ["color", "draw", "hold"], {}),
    NounEntry("coloring book", "en", "entertainment", True, ["color", "open", "fill"], {}),
    NounEntry("paint", "en", "entertainment", False, ["apply", "mix", "brush"], {"liquid": True}),
    NounEntry("canvas", "en", "entertainment", True, ["paint", "stretch", "hang"], {}),
    NounEntry("instrument", "en", "entertainment", True, ["play", "tune", "practice"], {}),
    NounEntry("guitar", "en", "entertainment", True, ["strum", "tune", "hold"], {}),
    NounEntry("piano", "en", "entertainment", True, ["play", "press", "tune"], {}),
    NounEntry("drum", "en", "entertainment", True, ["beat", "hit", "play"], {}),
    NounEntry("flute", "en", "entertainment", True, ["blow", "play", "hold"], {}),
    NounEntry("violin", "en", "entertainment", True, ["bow", "play", "tune"], {}),
    
    # ABSTRACT/COGNITIVE (for non-physical tasks)
    NounEntry("idea", "en", "abstract", True, ["think", "develop", "share"], {}),
    NounEntry("plan", "en", "abstract", True, ["make", "follow", "change"], {}),
    NounEntry("decision", "en", "abstract", True, ["make", "reconsider", "announce"], {}),
    NounEntry("problem", "en", "abstract", True, ["solve", "identify", "analyze"], {}),
    NounEntry("solution", "en", "abstract", True, ["find", "implement", "test"], {}),
    NounEntry("goal", "en", "abstract", True, ["set", "achieve", "pursue"], {}),
    NounEntry("task", "en", "abstract", True, ["complete", "assign", "prioritize"], {}),
    NounEntry("project", "en", "abstract", True, ["manage", "complete", "plan"], {}),
    NounEntry("meeting", "en", "abstract", True, ["schedule", "attend", "lead"], {}),
    NounEntry("appointment", "en", "abstract", True, ["schedule", "keep", "cancel"], {}),
    NounEntry("deadline", "en", "abstract", True, ["meet", "extend", "set"], {}),
    NounEntry("budget", "en", "abstract", True, ["create", "follow", "adjust"], {}),
    NounEntry("schedule", "en", "abstract", True, ["make", "follow", "adjust"], {}),
    NounEntry("list", "en", "abstract", True, ["make", "check", "update"], {}),
    NounEntry("email", "en", "abstract", True, ["write", "send", "read"], {}),
    NounEntry("message", "en", "abstract", True, ["send", "read", "reply"], {}),
    NounEntry("call", "en", "abstract", True, ["make", "answer", "return"], {}),
    NounEntry("conversation", "en", "abstract", True, ["have", "start", "end"], {}),
    NounEntry("presentation", "en", "abstract", True, ["give", "prepare", "create"], {}),
    NounEntry("report", "en", "abstract", True, ["write", "submit", "review"], {}),
    NounEntry("document", "en", "abstract", True, ["create", "edit", "save"], {}),
    NounEntry("file", "en", "abstract", True, ["save", "open", "delete"], {}),
    NounEntry("password", "en", "abstract", True, ["create", "remember", "change"], {}),
    NounEntry("account", "en", "abstract", True, ["create", "close", "manage"], {}),
    NounEntry("order", "en", "abstract", True, ["place", "track", "cancel"], {}),
    NounEntry("reservation", "en", "abstract", True, ["make", "confirm", "cancel"], {}),
    NounEntry("ticket", "en", "abstract", True, ["buy", "print", "show"], {}),
    NounEntry("trip", "en", "abstract", True, ["plan", "take", "cancel"], {}),
    NounEntry("route", "en", "abstract", True, ["plan", "follow", "change"], {}),
    NounEntry("direction", "en", "abstract", True, ["follow", "give", "ask"], {}),
    
    # PEOPLE (for social tasks)
    NounEntry("person", "en", "people", True, ["meet", "help", "greet"], {}),
    NounEntry("friend", "en", "people", True, ["call", "visit", "help"], {}),
    NounEntry("family", "en", "people", False, ["visit", "call", "help"], {}),
    NounEntry("parent", "en", "people", True, ["call", "visit", "help"], {}),
    NounEntry("child", "en", "people", True, ["teach", "care for", "play with"], {}),
    NounEntry("baby", "en", "people", True, ["hold", "feed", "change"], {}),
    NounEntry("elder", "en", "people", True, ["help", "care for", "visit"], {}),
    NounEntry("neighbor", "en", "people", True, ["greet", "help", "visit"], {}),
    NounEntry("colleague", "en", "people", True, ["collaborate", "meet", "email"], {}),
    NounEntry("boss", "en", "people", True, ["report to", "meet", "email"], {}),
    NounEntry("employee", "en", "people", True, ["manage", "train", "evaluate"], {}),
    NounEntry("customer", "en", "people", True, ["serve", "help", "greet"], {}),
    NounEntry("client", "en", "people", True, ["meet", "advise", "call"], {}),
    NounEntry("patient", "en", "people", True, ["examine", "treat", "care for"], {}),
    NounEntry("student", "en", "people", True, ["teach", "grade", "advise"], {}),
    NounEntry("teacher", "en", "people", True, ["consult", "email", "meet"], {}),
    NounEntry("doctor", "en", "people", True, ["visit", "consult", "call"], {}),
    NounEntry("nurse", "en", "people", True, ["call", "assist", "consult"], {}),
    NounEntry("guest", "en", "people", True, ["welcome", "serve", "entertain"], {}),
    NounEntry("host", "en", "people", True, ["thank", "assist", "call"], {}),
    NounEntry("pet", "en", "people", True, ["feed", "walk", "groom"], {}),
    NounEntry("dog", "en", "people", True, ["walk", "feed", "train"], {}),
    NounEntry("cat", "en", "people", True, ["feed", "pet", "groom"], {}),
]


# =============================================================================
# EXISTING DATASET TASK REFERENCES
# =============================================================================

BEHAVIOR_1K_SAMPLE_TASKS = [
    # Sample from BEHAVIOR-1K for seeding
    "watering plants", "setting table", "making bed", "doing laundry",
    "cleaning bathroom", "vacuuming floor", "washing dishes", "cooking pasta",
    "making coffee", "toasting bread", "frying egg", "boiling water",
    "chopping vegetables", "mixing salad", "serving food", "clearing table",
    "loading dishwasher", "unloading dishwasher", "taking out trash",
    "recycling", "mopping floor", "dusting furniture", "organizing closet",
    "folding clothes", "ironing clothes", "hanging clothes", "packing suitcase",
    "unpacking groceries", "storing food", "cleaning refrigerator",
    "defrosting freezer", "cleaning oven", "cleaning microwave",
    "wiping counters", "scrubbing sink", "cleaning toilet", "changing sheets",
    "fluffing pillows", "opening curtains", "closing blinds", "turning on lights",
    "adjusting thermostat", "locking door", "unlocking door", "answering door",
    "signing for package", "wrapping gift", "writing card", "addressing envelope",
    "feeding pet", "walking dog", "grooming pet", "cleaning litter box",
    "watering garden", "mowing lawn", "raking leaves", "shoveling snow",
    "washing car", "changing tire", "checking oil", "filling gas tank",
]

ONET_SAMPLE_WORK_TASKS = [
    # Sample from O*NET for occupational tasks
    "typing documents", "answering phone calls", "scheduling meetings",
    "filing paperwork", "sending emails", "taking notes", "giving presentations",
    "attending meetings", "managing calendar", "booking travel",
    "processing invoices", "reconciling accounts", "preparing reports",
    "analyzing data", "creating spreadsheets", "updating databases",
    "greeting visitors", "directing calls", "sorting mail",
    "copying documents", "shredding papers", "ordering supplies",
    "stocking shelves", "operating register", "handling cash",
    "wrapping purchases", "processing returns", "assisting customers",
    "demonstrating products", "arranging displays", "taking inventory",
    "receiving shipments", "unpacking boxes", "labeling items",
    "operating machinery", "assembling products", "inspecting quality",
    "packaging goods", "loading trucks", "driving forklift",
    "welding metal", "cutting materials", "measuring dimensions",
    "reading blueprints", "installing fixtures", "testing equipment",
    "diagnosing problems", "repairing devices", "replacing parts",
    "cleaning equipment", "maintaining tools", "following safety procedures",
]

ADL_IADL_TASKS = [
    # Activities of Daily Living (ADL) and Instrumental ADL
    # Basic ADL
    "bathing", "showering", "washing face", "brushing teeth", "combing hair",
    "shaving", "applying deodorant", "dressing", "undressing", "putting on shoes",
    "tying shoelaces", "buttoning shirt", "zipping jacket", "eating", "drinking",
    "using utensils", "cutting food", "chewing", "swallowing", "toileting",
    "wiping", "flushing", "washing hands", "transferring from bed",
    "transferring to chair", "walking", "climbing stairs", "getting in car",
    "getting out of car", "using wheelchair", "using walker", "using cane",
    
    # Instrumental ADL
    "preparing meals", "cooking", "using stove", "using oven", "using microwave",
    "cleaning house", "doing laundry", "ironing", "sewing", "mending clothes",
    "managing medications", "taking pills", "using inhaler", "applying cream",
    "measuring blood pressure", "checking blood sugar", "managing finances",
    "paying bills", "writing checks", "using ATM", "shopping for groceries",
    "shopping for clothes", "comparing prices", "using coupons",
    "using telephone", "making calls", "answering calls", "sending texts",
    "using computer", "browsing internet", "sending emails", "using transportation",
    "driving car", "taking bus", "calling taxi", "reading map", "following directions",
]


def get_seed_verbs(language: str = "en") -> list[VerbEntry]:
    """Get seed verbs for a language."""
    if language == "en":
        return ENGLISH_VERBS
    else:
        # For other languages, would need translation or separate lists
        return []


def get_seed_nouns(language: str = "en") -> list[NounEntry]:
    """Get seed nouns for a language."""
    if language == "en":
        return ENGLISH_NOUNS
    else:
        return []


def get_existing_task_seeds() -> list[str]:
    """Get existing task references from datasets."""
    return BEHAVIOR_1K_SAMPLE_TASKS + ONET_SAMPLE_WORK_TASKS + ADL_IADL_TASKS


def export_seeds_to_json(output_path: str):
    """Export all seeds to JSON for inspection."""
    data = {
        "verbs": {
            "en": [
                {
                    "verb": v.verb,
                    "category": v.category,
                    "transitivity": v.transitivity,
                    "typical_objects": v.typical_objects,
                    "physical_involvement": v.physical_involvement,
                }
                for v in ENGLISH_VERBS
            ]
        },
        "nouns": {
            "en": [
                {
                    "noun": n.noun,
                    "category": n.category,
                    "typical_actions": n.typical_actions,
                    "physical_properties": n.physical_properties,
                }
                for n in ENGLISH_NOUNS
            ]
        },
        "existing_tasks": get_existing_task_seeds(),
    }
    
    with open(output_path, 'w') as f:
        json.dump(data, f, indent=2)
    
    return data
